server {
    listen 80;
    server_name gui.mujiu.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name gui.mujiu.net;

    ssl_certificate /etc/letsencrypt/live/gui.mujiu.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gui.mujiu.net/privkey.pem;

    root /var/www/gui;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
